#define GG(x)  sub(gg, ':', ':', x)
!#define GG(x)  gg%data( :, :, x-1)
#define EE(x)  sub(ee, ':', ':', x)
!#define EE(x)  ee%data( :, :, x-1)
#define A(x)   sub(a,  ':', ':', x)
!#define A(x)   a%data(:, :, x-1)
#define C(x)   sub(c,  ':', ':', x)
!#define C(x)   c%data(:, :, x-1)

#define KH(x) kh%data(:,:,x-1)

#define DHF_3D(x) dhf_3d%data(:,:,x-1)

#define VF(x)  sub(vf, ':', ':', x)
!#define VF(x)  vf%data(:, :, x-1)
#define VB(x)  sub(vb, ':', ':', x)
#define UF(x)  sub(uf, ':', ':', x)
!#define UF(x)  uf%data(:, :, x-1)
#define UB(x)  sub(ub, ':', ':', x)
!#define TF(x)  sub(tf, ':', ':', x)
#define TF(x)  tf%data(:, :, x-1)
#define FF(x)  sub(ff, ':', ':', x)
!#define FF(x)  ff%data(:, :, x-1)
!#define TB(x)  sub(tb, ':', ':', x)
#define TB(x)  tb%data(:, :, x-1)
#define RAD(x) sub(rad, ':', ':', x)
!#define RAD(x) rad%data(:, :, x-1)
#define FRAD   frad%data(:, :, 0)
#define Q2F(x) sub(q2f, ':', ':', x)
!#define Q2F(x) q2f%data(:, :, x-1)
#define Q2LF(x) sub(q2lf, ':', ':', x)
!#define Q2LF(x) q2lf%data(:, :, x-1)
#define L(x)    sub(l, ':', ':', x)
!#define L(x)    l%data(:, :, x-1)
!#define L0(x)   l0%data(:, :, x-1)
#define L0(x)    sub(l0, ':', ':', x)
#define DTEF(x) sub(dtef, ':', ':', x)
!#define DTEF(x) dtef%data(:, :, x-1)
#define KN(x)   sub(kn, ':', ':', x)
!#define KN(x)   kn%data(:, :, x-1)
#define DZ(x)   sub(dz, ':',':',x)
!#define DZ(x)   dz%data(:, :, x-1)
!#define DZ_3D(x)   sub(dz_3d, ':',':',x)
!#define DZ_3D(x)   dz_3d%data(:, :, x-1)
!#define DH_3D(x)   sub(dh_3d, ':',':',x)
#define DH_3D(x)   dh_3d%data(:, :, x-1)
#define DH_2D      dh%data(:, :,0)
#define TPS_2D     tps%data(:, :,0)
#define UTAU2      utau2%data(:,:,0)
#define FSURF_2D   fsurf%data(:,:,0) 
#define WFSURF_2D  wfsurf%data(:,:,0) 
#define WUSURF_2D  wusurf%data(:,:,0) 
#define WVSURF_2D  wvsurf%data(:,:,0) 
#define WUBOT_2D   wubot%data(:,:,0) 
#define WVBOT_2D   wvbot%data(:,:,0)

#define EGF_3D(x)  egf_3d%data(:,:,x-1) 
#define EGF_2D     egf%data(:,:,0)

#define EGB_3D(x)  egb_3d%data(:,:,x-1) 
#define EGB_2D     egb%data(:,:,0)

#define D_3D(x)    d_3d%data(:,:,x-1) 
#define D_2D       d%data(:,:,0)

#define DT_3D(x)   dt_3d%data(:,:,x-1) 
#define DT_2D      dt%data(:,:,0)

#define ETF_3D(x)  etf_3d%data(:,:,x-1) 
#define ETF_2D     etf%data(:,:,0)

#define ETB_3D(x)  etb_3d%data(:,:,x-1) 
#define ETB_2D     etb%data(:,:,0)

#define E_ATMOS_3D(x)  e_atmos_3d%data(:,:,x-1)
#define E_ATMOS_2D     e_atmos%data(:,:,0)

#define U(x)       u%data(:,:,x-1) 
#define V(x)       v%data(:,:,x-1)

#define SUM_UDZ1    sum_udz%data(:,:,0)
#define SUM_VDZ1    sum_vdz%data(:,:,0)

#define AVE_UT     ave_ut%data(:,:,0)
#define AVE_VT     ave_vt%data(:,:,0)

#define FLUC_U(x)  FLUC_U%data(:,:,x-1)
#define FLUC_V(x)  FLUC_V%data(:,:,x-1)

#define W(x)       w%data(:,:,x-1)
#define DEL_W(x)   del_w%data(:,:,x-1)
#define FSM_3D(x)  fsm_3d%data(:,:,x-1)

#define VFLUX      vflux%data(:,:,0)

!#define Z_3D(x,y)    z_3d%data(x-1,y-1,:)
!#define ZZ_3D(x,y)   zz_3d%data(x-1,y-1,:)
!#define DZ_3D(x,y)   dz_3d%data(x-1,y-1,:)
!#define DZZ_3D(x,y)  dzz_3d%data(x-1,y-1,:)

!#define Z_1D        z%data(0,0,:)
!#define ZZ_1D       zz%data(0,0,:)
!#define DZ_1D       dz%data(0,0,:)
!#define DZZ_1D      dzz%data(0,0,:)

#define DX_3D(x)   dx_3d%data(:,:,x-1)
#define DY_3D(x)   dy_3d%data(:,:,x-1)
#define COR_3D(x)  cor_3d%data(:,:,x-1)
#define ART_3D(x)  art_3d%data(:,:,x-1)
#define ARU_3D(x)  aru_3d%data(:,:,x-1)
#define ARV_3D(x)  arv_3d%data(:,:,x-1)
#define DUM_3D(x)  dum_3d%data(:,:,x-1)
#define DVM_3D(x)  dvm_3d%data(:,:,x-1)
#define H_3D(x)    h_3d%data(:,:,x-1)

#define DX_2D       dx%data(:,:,0)
#define DY_2D       dy%data(:,:,0)
#define COR_2D      cor%data(:,:,0)
#define ART_2D      art%data(:,:,0)
#define ARU_2D      aru%data(:,:,0)
#define ARV_2D      arv%data(:,:,0)
#define DUM_2D      dum%data(:,:,0)
#define DVM_2D      dvm%data(:,:,0)
#define H_2D        h%data(:,:,0)
#define FSM_2D      fsm%data(:,:,0)

#define AYF_V(i)      ayf_v%data(:,:,i-1)
#define AXF_U(i)      axf_u%data(:,:,i-1)

#define CURV_X(i)      curv_x%data(:,:,i-1)
#define CURV_Y(i)      curv_y%data(:,:,i-1)

#define CURV(i)    curv%data(:,:,i-1)
#define DXB_AXF_DY dxb_axf_dy%data(:,:,0)
#define DYB_AYF_DX dyb_ayf_dx%data(:,:,0)

#define AAM(i)   aam%data(:,:,i-1)
